export { default as Carousel } from './Carousel';
export { default as CarouselNew } from './CarouselNew';
export { default as Header } from './Header';
export { default as Benefits } from './Benefits';
export { default as FormSection } from './FormSection';
export { default as Newsletter } from './Newsletter';
export { default as CookiesWarning } from './CookiesWarning';
export { default as Footer } from './Footer';
export { default as Main } from './Main';
